drop table product if exists;
create table product (id bigint generated by default as identity, current_price decimal(19,2) not null, last_updated timestamp, name varchar(255) not null, primary key (id), description varchar(255));

insert into product(id, current_price, last_updated, name) values (100, 700, '2020-03-04', 'Iphone11');
insert into product(id, current_price, last_updated, name) values (101, 10000, '2020-03-04', 'Iphone22');