create table "user"(id bigint generated by default as identity, username varchar(255) not null, password varchar(255) not null);

insert into "user"(id,username, password) values(1, 'admin', '$2a$10$2pCjrUTj9cZtbM0W5.bLmeUiS0W3AkrbTOP3OwO/V4hPIugX1guu6');